library(openintro)

pdf("fat_tails.pdf", width = 10, height = 5)
par(mfrow=c(1,2), mar = c(4,4,0.5,0.5), cex.axis = 1.5, cex.lab = 1.5)
d = rt(1000,df=5)
#d = d[d<10 & d > -10]
hist(d,freq=FALSE,breaks=25,main="",xlab="",ylab="", border = COL[6,2])
mu = mean(d)
sd = sd(d)
x = seq(mu-3*sd,mu+3*sd,len=100)
y = dnorm(x,mean=mu,sd=sd)
lines(x,y,col=COL[1],lwd=2)
qqnorm(d,axes=FALSE, col = COL[1,4], main = "", pch = 19)
axis(1)
axis(2)
qqline(d, col = COL[1])
dev.off()

pdf("skinny_tails.pdf", width = 10, height = 5)
par(mfrow=c(1,2), mar = c(4,4,0.5,0.5), cex.axis = 1.5, cex.lab = 1.5)
d = rnorm(1000)
d = d[d<1.5 & d > -1.5]
hist(d,freq=FALSE,breaks=15,main="",xlab="",ylab="",xlim=c(-2.5,2.5),ylim=c(0,0.55), border = COL[6,2])
mu = mean(d)
sd = sd(d)
x = seq(mu-3*sd,mu+3*sd,len=100)
y = dnorm(x,mean=mu,sd=sd)
lines(x,y,col=COL[1],lwd=2)
qqnorm(d,axes=FALSE, col = COL[1,4], main = "", pch = 19)
axis(1)
axis(2)
qqline(d, col = COL[1])
dev.off()

pdf("right_skew.pdf", width = 10, height = 5)
par(mfrow=c(1,2), mar = c(4,4,0.5,0.5), cex.axis = 1.5, cex.lab = 1.5)
set.seed(100)
d = rlnorm(1000)
d = d[d<10]
hist(d,freq=FALSE,breaks=15,main="",xlab="",ylab="", border = COL[6,2])
mu = mean(d)
sd = sd(d)
x = seq(mu-3*sd,mu+3*sd,len=100)
y = dnorm(x,mean=mu,sd=sd)
lines(x,y,col=COL[1],lwd=2)
qqnorm(d,axes=FALSE, col = COL[1,4], main = "", pch = 19)
axis(1)
axis(2)
qqline(d, col = COL[1])
dev.off()

pdf("left_skew.pdf", width = 10, height = 5)
par(mfrow=c(1,2), mar = c(4,4,0.5,0.5), cex.axis = 1.5, cex.lab = 1.5)
d = rlnorm(1000)
d = 10-d[d<10]
hist(d,freq=FALSE,breaks=15,main="",xlab="",ylab="", border = COL[6,2])
mu = mean(d)
sd = sd(d)
x = seq(mu-3*sd,mu+3*sd,len=100)
y = dnorm(x,mean=mu,sd=sd)
lines(x,y,col=COL[1], lwd=2)
qqnorm(d,axes=FALSE, col = COL[1,4], main = "", pch = 19)
axis(1)
axis(2)
qqline(d, col = COL[1])
dev.off()